"""lead and understudy

Revision ID: 561d3656cce8
Revises: e2eb513d2743
Create Date: 2023-05-11 16:01:48.324049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561d3656cce8'
down_revision = 'e2eb513d2743'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
