"""actors in Role

Revision ID: 8a01def286c8
Revises: 2f83fb589ba1
Create Date: 2023-05-11 15:45:52.049268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a01def286c8'
down_revision = '2f83fb589ba1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
