"""call_back

Revision ID: 9a074df24c92
Revises: fb4b0e3ce2da
Create Date: 2023-05-11 15:25:46.509212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a074df24c92'
down_revision = 'fb4b0e3ce2da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
