"""locations

Revision ID: e2eb513d2743
Revises: fecb0c49faef
Create Date: 2023-05-11 15:58:41.716145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2eb513d2743'
down_revision = 'fecb0c49faef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
