"""fix typo in actors

Revision ID: fecb0c49faef
Revises: bc48bf900862
Create Date: 2023-05-11 15:57:15.055860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecb0c49faef'
down_revision = 'bc48bf900862'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
